### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by paazmaya** [mgreter/sass2scss#18]
Which license would be suitable for this project?

http://opensource.org/licenses/

Perhaps MIT?

Once selected, mention it in every file.

**Comment by mgreter** [comment]
https://github.com/mgreter/sass2scss/blob/master/LICENSE !?

**Comment by paazmaya** [comment]
Seems I am :see_no_evil: 

Could it be mentioned and linked to in every source file and README.md?

**Comment by paazmaya** [comment]
Wil make a PR
